@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.westongame.smokingiron.datagen;

import com.mojang.blaze3d.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;